version: 2
sources:
  - name: taxi_raw
    database: NYC_TAXI_DB
    schema: RAW_DATA
    tables:
      - name: yellow_trips
        freshness: 
          warn_after: {count: 7, period: day}
        columns:
          - name: tpep_pickup_datetime
        tests:
          - not_null
      - name: taxi_zones
      - name: weather
            
        